language: python
python:
  - 3.11.4

# Update pip to the latest version
before_install:
  - python --version
  - pip install -U pip

install:
  - pip install -r requirements.txt

script:
  - python -m unittest main.py

deploy:
  provider: pypi
  username: "__token__"
  password: "$PYPI_TOKEN"
  on:
    branch: main
